PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX she: <http://data-iremus.huma-num.fr/ns/sherlock#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
WHERE {
  GRAPH <http://data-iremus.huma-num.fr/graph/mercure-galant> {
    VALUES ?P140 { 
      <http://data-iremus.huma-num.fr/id/fcdada80-5f0e-48ff-af41-b8b685b92f03>
      <http://data-iremus.huma-num.fr/id/7e3c0ca1-a618-416f-a06d-46d69b0cd090>
      <http://data-iremus.huma-num.fr/id/7e3c0ca1-a618-416f-a06d-46d69b0cd090>
      <http://data-iremus.huma-num.fr/id/724e924b-5c2d-4954-b4ce-0b6216be3642>
      <http://data-iremus.huma-num.fr/id/724e924b-5c2d-4954-b4ce-0b6216be3642>
      <http://data-iremus.huma-num.fr/id/9c52f791-2f08-4fa9-9fb5-dd6f14ae182f>
      <http://data-iremus.huma-num.fr/id/5d091b78-42a8-4c86-aa1b-0277d00adce2>
      <http://data-iremus.huma-num.fr/id/724e924b-5c2d-4954-b4ce-0b6216be3642>
      <http://data-iremus.huma-num.fr/id/9c52f791-2f08-4fa9-9fb5-dd6f14ae182f>
      <http://data-iremus.huma-num.fr/id/55517182-73ec-4ebe-bd63-77c3c9387d8d>
      <http://data-iremus.huma-num.fr/id/fcdada80-5f0e-48ff-af41-b8b685b92f03>
      <http://data-iremus.huma-num.fr/id/f5bf1180-fd54-45a2-902b-492a37084ad0>
    }

    ?E13 crm:P140_assigned_attribute_to ?P140 .
    ?E13 crm:P177_assigned_property_type ?P177 .
    ?E13 crm:P141_assigned ?P141 .

    # Trouver un label signifiant pour l'entité P141
    OPTIONAL {
      GRAPH ?P141_label_g {
        {
          VALUES ?P141_label_p { crm:P1_is_identified_by crm:P102_has_title rdfs:label }
          ?P141 ?P141_label_p ?P141_label .
          FILTER(isLiteral(?P141_label)) .
        }
        UNION
        {
          VALUES ?P141_label_p { crm:P1_is_identified_by crm:P102_has_title }
          ?P141 ?P141_label_p ?P141_label_r .
          GRAPH ?P141_label_g {
            VALUES ?e41_type { crm:E35_Title crm:E41_Appellation crm:E42_Identifier }
            ?P141_label_r rdf:type ?e41_type .
            ?P141_label_r rdfs:label ?label .
          }
        }
      } 
    }
  }
}